apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-spc
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "91304316-9f04-4b2e-89bd-31a7c4c5a3c3"
    keyvaultName: "myKeyVault-1099"
    cloudName: "AzurePublicCloud"
    objects: |
      array:
        - |
          objectName: myKeyVaultSecret
          objectType: secret
        - |
          objectName: generated-certificate
          objectType: key
    tenantId: "e994072b-523e-4bfe-86e2-442c5e10b244"
